fix code
ca-risken/doc pull request #97
Opened 2022-09-14 11:03 UTC by iiiidaaa

- dependencyの記述を追加しました
- gitleaksのデータソース設定記述していたGitHubの設定,GHESの記述部分をgithub_setting.mdに移しました
  - gitleaks,dependencyで共通に使用する設定のためです
- 画面の更新に当たって、gitleaksの記述、画像を変更しました

2022-09-14 14:42 UTC, gassara-kys commented on docs/code/dependency_datasource.md
> +    発見した場合、強制的にデータ削除する可能性があります
この注意書きは不要かと思うのですがどうですかね？:eyes:

2022-09-14 14:42 UTC, gassara-kys commented on docs/code/dependency_scan.md
> +6. 上記のように手動スキャンの他に連携済みのDataSourceは定期的に（日次）スケジュール実行されます
日次スキャンかどうかは、システム管理者の設定次第（CronJobのスケジュール次第）なので日次は削除した方がよいかと思います。（日次という言葉が他でも使われてしまっていますが、、、）

2022-09-14 14:42 UTC, gassara-kys commented on docs/code/github_setting.md
> +    発見した場合、強制的にデータ削除する可能性があります
こちらも不要かと思いました。公開されてるリポジトリ、または自分の認証情報でgit cloneするだけなので

2022-09-14 14:42 UTC, gassara-kys commented on docs/code/dependency_datasource.md
> +    - RISKEN環境からcloneできないもの
スキャンの制約事項はGitleaksと共通なので、GitHubのページで一箇所にまとめます？

2022-09-14 14:44 UTC, gassara-kys commented on docs/code/dependency_scan.md
> +6. 上記のように手動スキャンの他に連携済みのDataSourceは定期的に（日次）スケジュール実行されます
https://docs.security-hub.jp/code/gitleaks_scan/?h=%E6%97%A5%E6%AC%A1

2022-09-15 02:25 UTC, mmmknt requested changes

2022-09-15 02:25 UTC, mmmknt commented on docs/admin/param_code.md
> +
Gitleaksと共通のパラメータは `Code共通` の方に記載した方が見通しが良くなるかと思います

2022-09-15 02:25 UTC, mmmknt commented on docs/admin/param_code.md
> +| **LIMIT_REPOSITORY_SIZE_KB** | Gitleaksスキャン時のリポジトリサイズLimit値 | | `500000` |
GitleaksではなくDependency用のサービスですよね

2022-09-15 08:18 UTC, iiiidaaa commented on docs/code/dependency_datasource.md
> +    発見した場合、強制的にデータ削除する可能性があります
注意書きを削除しました。
gitleaksも同様にPATの範囲内でのスキャンしか行わないため、注意書きを削除しています。

2022-09-15 08:19 UTC, iiiidaaa commented on docs/code/dependency_scan.md
> +6. 上記のように手動スキャンの他に連携済みのDataSourceは定期的に（日次）スケジュール実行されます
`(日次)`の記載を削除しました。(定期的に実行されることの記述は残しています)
gitleaksにも同様の修正を行いました。

2022-09-15 08:19 UTC, iiiidaaa commented on docs/code/github_setting.md
> +    発見した場合、強制的にデータ削除する可能性があります
注意書きを削除しました。

2022-09-15 08:21 UTC, iiiidaaa commented on docs/code/dependency_datasource.md
> +    - RISKEN環境からcloneできないもの
dependency,gitleaksからこの制約事項の記述を削除し、GitHubのページに記載する様に修正しました。
また、一部制約内容が異なる(ArchiveはDependencyではスキャンする)ためその旨を記載する様にしています。
```
    - リポジトリのステータスが以下のもの
        - `Archived` (Gitleaksのみ対象外になります)
        - `Disabled`
        - `Forkリポジトリ`
            - ＊[Forkリポジトリ :octicons-link-external-24:](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo){ target="_blank" } とは一般的にはオリジナルリポジトリへの貢献（修正の提案）のために作成されるリポジトリです
    - リポジトリのサイズによる制限があります（詳細はシステム管理者に問い合わせてください）
    - RISKEN環境からcloneできないもの
```

2022-09-15 08:22 UTC, iiiidaaa commented on docs/admin/param_code.md
> +| **LIMIT_REPOSITORY_SIZE_KB** | Gitleaksスキャン時のリポジトリサイズLimit値 | | `500000` |
`Gitleaksスキャン時のリポジトリサイズLimit値` から　`Dependencyスキャン時のリポジトリサイズLimit値`へと修正しました。

2022-09-15 08:55 UTC, iiiidaaa commented on docs/admin/param_code.md
> +
`CODE_DATA_KEY`と`GITHUB_DEFAULT_TOKEN`をCode共通に移動しました。

その他の共通しているパラメータ(DEBUG等)はDataSourceで個別に設定できるよう、Parameter Storeの保存先を変更しているため分けて記載しています。

2022-09-15 09:13 UTC, mmmknt approved these changes
LGTM

2022-09-15 09:14 UTC, gassara-kys approved these changes
LGTM

2022-09-16 01:42 UTC, merged